openapi: 3.0.0
info:
  title: Timetable Restinga Fetcher
  version: 1.0.0
  description: ""
servers:
  - url: "http://localhost:3000"
paths:
  /api/teachers:
    parameters: []
    get:
      summary: Teachers
      parameters: []
      responses:
        "200":
          headers:
            X-Powered-By:
              schema:
                type: string
              example: Express
            Content-Type:
              schema:
                type: string
              example: application/json; charset=utf-8
            Content-Length:
              schema:
                type: integer
              example: "29356"
            ETag:
              schema:
                type: string
              example: W/"72ac-3ahywBQ8vMGCk5sZktZhZu+fRfI"
            Date:
              schema:
                type: string
              example: Sat, 28 Jun 2025 06:39:40 GMT
            Connection:
              schema:
                type: string
              example: keep-alive
            Keep-Alive:
              schema:
                type: string
              example: timeout=5
          description: Teachers
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      format: utc-millisec
                    firstname:
                      type: string
                    lastname:
                      type: string
                    short:
                      type: string
                    cb_hidden:
                      type: boolean
                    subname:
                      type: string
                    expired:
                      type: boolean
  /api/subjects:
    parameters: []
    get:
      summary: Subjects
      parameters: []
      responses:
        "200":
          headers:
            X-Powered-By:
              schema:
                type: string
              example: Express
            Content-Type:
              schema:
                type: string
              example: application/json; charset=utf-8
            Content-Length:
              schema:
                type: integer
              example: "23767"
            ETag:
              schema:
                type: string
              example: W/"5cd7-4grK+1kuQrYiZCcoVeFZQiP+YDU"
            Date:
              schema:
                type: string
              example: Sat, 28 Jun 2025 06:41:00 GMT
            Connection:
              schema:
                type: string
              example: keep-alive
            Keep-Alive:
              schema:
                type: string
              example: timeout=5
          description: Subjects
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      format: utc-millisec
                    name:
                      type: string
                    short:
                      type: string
  /api/classrooms:
    parameters: []
    get:
      summary: Classrooms
      parameters: []
      responses:
        "200":
          headers:
            X-Powered-By:
              schema:
                type: string
              example: Express
            Content-Type:
              schema:
                type: string
              example: application/json; charset=utf-8
            Content-Length:
              schema:
                type: integer
              example: "2247"
            ETag:
              schema:
                type: string
              example: W/"8c7-/ENSpk4NCvHg5+ACFlhG86Z4iiI"
            Date:
              schema:
                type: string
              example: Sat, 28 Jun 2025 06:41:15 GMT
            Connection:
              schema:
                type: string
              example: keep-alive
            Keep-Alive:
              schema:
                type: string
              example: timeout=5
          description: Classrooms
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      format: utc-millisec
                    short:
                      type: string
  /api/classes:
    parameters: []
    get:
      summary: Classes
      parameters: []
      responses:
        "200":
          headers:
            X-Powered-By:
              schema:
                type: string
              example: Express
            Content-Type:
              schema:
                type: string
              example: application/json; charset=utf-8
            Content-Length:
              schema:
                type: integer
              example: "2861"
            ETag:
              schema:
                type: string
              example: W/"b2d-VgTEih0cPQlg/kPjrHCQijBU8Cg"
            Date:
              schema:
                type: string
              example: Sat, 28 Jun 2025 06:41:31 GMT
            Connection:
              schema:
                type: string
              example: keep-alive
            Keep-Alive:
              schema:
                type: string
              example: timeout=5
          description: Classes
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      format: utc-millisec
                    name:
                      type: string
                      format: color
                    short:
                      type: string
                      format: color
  /api/periods:
    parameters: []
    get:
      summary: Periods
      parameters: []
      responses:
        "200":
          headers:
            X-Powered-By:
              schema:
                type: string
              example: Express
            Content-Type:
              schema:
                type: string
              example: application/json; charset=utf-8
            Content-Length:
              schema:
                type: integer
              example: "1397"
            ETag:
              schema:
                type: string
              example: W/"575-9BFvWNwmp0x7GbEfBC/KxmUQxG4"
            Date:
              schema:
                type: string
              example: Sat, 28 Jun 2025 06:41:42 GMT
            Connection:
              schema:
                type: string
              example: keep-alive
            Keep-Alive:
              schema:
                type: string
              example: timeout=5
          description: Periods
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      format: utc-millisec
                    name:
                      type: string
                      format: utc-millisec
                    short:
                      type: string
                      format: utc-millisec
                    period:
                      type: string
                      format: utc-millisec
                    starttime:
                      type: string
                      format: style
                    endtime:
                      type: string
  /api/dayparts:
    parameters: []
    get:
      summary: Dayparts
      parameters: []
      responses:
        "200":
          headers:
            X-Powered-By:
              schema:
                type: string
              example: Express
            Content-Type:
              schema:
                type: string
              example: application/json; charset=utf-8
            Content-Length:
              schema:
                type: integer
              example: "151"
            ETag:
              schema:
                type: string
              example: W/"97-ajP06KQ3PHIHxjiHTPLsdHPY3DQ"
            Date:
              schema:
                type: string
              example: Sat, 28 Jun 2025 06:41:56 GMT
            Connection:
              schema:
                type: string
              example: keep-alive
            Keep-Alive:
              schema:
                type: string
              example: timeout=5
          description: Dayparts
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    starttime:
                      type: string
                      format: style
                    endtime:
                      type: string
  /api/dates:
    parameters: []
    get:
      summary: Dates
      parameters: []
      responses:
        "200":
          headers:
            X-Powered-By:
              schema:
                type: string
              example: Express
            Content-Type:
              schema:
                type: string
              example: application/json; charset=utf-8
            Content-Length:
              schema:
                type: integer
              example: "318"
            ETag:
              schema:
                type: string
              example: W/"13e-VrJ3bNCnWgurSobHXIE2BIT2LeM"
            Date:
              schema:
                type: string
              example: Sat, 28 Jun 2025 06:42:09 GMT
            Connection:
              schema:
                type: string
              example: keep-alive
            Keep-Alive:
              schema:
                type: string
              example: timeout=5
          description: Dates
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      format: date
                    tt_num:
                      type: string
                      format: utc-millisec
                    tt_day:
                      type: integer
  /api/event_types:
    parameters: []
    get:
      summary: Event types
      parameters: []
      responses:
        "200":
          headers:
            X-Powered-By:
              schema:
                type: string
              example: Express
            Content-Type:
              schema:
                type: string
              example: application/json; charset=utf-8
            Content-Length:
              schema:
                type: integer
              example: "2625"
            ETag:
              schema:
                type: string
              example: W/"a41-z/gb6+MHdHjHgsQOOx5JVrgp5sQ"
            Date:
              schema:
                type: string
              example: Sat, 28 Jun 2025 06:42:25 GMT
            Connection:
              schema:
                type: string
              example: keep-alive
            Keep-Alive:
              schema:
                type: string
              example: timeout=5
          description: Event types
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    name:
                      type: string
                    icon:
                      type: string

